# Generated by Django 5.1.4 on 2026-08-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_wallet_subscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'История подписки', 'verbose_name_plural': 'История подписок'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Транзакция кошелька', 'verbose_name_plural': 'Транзакции кошелька'},
        ),
    ]
