# Generated by Django 5.1.4 on 2026-08-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_ai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('telegram', 'Telegram-бот'), ('email', 'Email (SMTP)'), ('webhook', 'Webhooks'), ('google_sheets', 'Google Sheets'), ('csv_export', 'CSV-экспорт'), ('discord', 'Discord'), ('slack', 'Slack'), ('google_analytics', 'Google Analytics')], max_length=40),
        ),
    ]
