# Generated by Django 5.1.4 on 2026-08-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_integration_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рабочее пространство', 'verbose_name_plural': 'Рабочие пространства'},
        ),
        migrations.AlterModelOptions(
            name='workspacemember',
            options={'ordering': ['joined_at'], 'verbose_name': 'Участник команды', 'verbose_name_plural': 'Команда'},
        ),
    ]
